on: [push]

name: CI

jobs:
  docker:
    name: CI/Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v9
      - run: nix-build docker.nix
